#!/usr/bin/php
<?php echo "\n";


$addon_name = basename(dirname(__FILE__));
$has_themes = (file_exists('src/theme') && is_dir('src/theme'));


// VERSION
echo "Trying to determine release version...\n";
preg_match('/[0-9a-f]{7} [(](?:HEAD, )?tag: v([^,)]+)/', `git log --oneline --decorate`, $m);

if (isset($m[1])) {
    $version = $m[1];
    echo "Found version $version...\n";
}
else {
    echo "Could not determine version...\n";
    echo "Exiting...\n";
    exit(1);
}
echo "\n";


// PREP
echo "Cleaning previous release...\n";
`rm -rf tmp release/`;

echo "Creating clean structure...\n";
`mkdir -p release/system/expressionengine/third_party`;


// ADD-ON
echo "Copying and renaming add-on into clean structure...\n";
`cp -R src/ release/system/expressionengine/third_party/$addon_name`;


// THEME
if ($has_themes) {
    echo "Creating theme structure...\n";
    `mkdir -p release/themes/third_party`;

    echo "Moving theme into place...\n";
    `mv release/system/expressionengine/third_party/$addon_name/theme release/themes/third_party/$addon_name`;
}
echo "\n";


// ZIP
echo "Zipping release...\n";
`cd release`;
`zip -r $addon_name-$version.zip *`;
